### ISSUE TITLE
multiplier at zone is not calculated correctly

### ISSUE THREAD

**Issue by DanDan800** [jeroenterheerdt/HAsmartirrigation#163]
### What happened?

Multiplier is not calculated correctly.
For the calculations only the first number is used e. g. : 
0,5 => 0
1,2 => 1
... 
![Screenshot_20230819_204502_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/7a4972c0-a766-4b7f-bc6a-c6006039c0b9)

Multiplier with dot (e.g. 0.5) can not be entered.
By the way : dot and comma are not used consistently.( The info calculation shows dots.) I didn’t know, which is the preferred syntax 

### How to reproduce

Can be reproduced by changing the multiplier and  execution of a manual calculation. 

### Which version are you running?

Beta 13

### Diagnostics file

- [X] I have attached a diagnostics file

[config_entry-smart_irrigation-d309574885fe55cb4f63702993289a78-5.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12386548/config_entry-smart_irrigation-d309574885fe55cb4f63702993289a78-5.txt)

**Comment by jeroenterheerdt** [comment]
Thanks a lot for opening the issue as requested. I love in the US so for me the decimal separator is '.'. Can you try what happens if you use a decimal number for size and throughput using the comma as decimal separator. Does that store the decimals? I think it should as HA should take care of it. Please try and let me know. You have a good point about the use of the dot in the explanation, that should be locale dependent (I. E. A dot for me, a comma for you). Please try the above and let me know! Thanks again!

**Comment by DanDan800** [comment]
Hi, size and throughput store the comma value as expected. Only the multiplier looses the comma (even when only switching between the taps).


I am now on beta 14. 
Calculation is not working right now, but I think there has already been opened a separate issue for that. 
(Calculate zone Rasen gesamt failed: no data available.)

**Comment by jeroenterheerdt** [comment]
ok, decimal problem for multiplier should be fixed in beta 15

**Comment by DanDan800** [comment]
Now I am on beta 16. Sorry to tell you, that behavior has not changed. Multiplier 0,5 still is calculated as 0.
Multiplier with '.' can not be entered. 
![Screenshot_20230821_104401_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/a568c7fa-b920-4a6d-8c99-796137d66b60)

**Comment by jeroenterheerdt** [comment]
Can you please add another diagnostic file? I was able to enter a decimal value for multiplier and have it stored and used, so not sure what is going on. I guess I will have to set up a HA instance with German locale then... Your diagnostics file allows me to replicate exactly what you have, so please add that in (it might have changed since the previous one you shared). Thanks

**Comment by DanDan800** [comment]
Sure, no problem. 

[config_entry-smart_irrigation-1391110b7b1dfdb9babb7cdd3396bfa3.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12397376/config_entry-smart_irrigation-1391110b7b1dfdb9babb7cdd3396bfa3.txt)

**Comment by jeroenterheerdt** [comment]
fixed in beta 17, please verify and close.

**Comment by DanDan800** [comment]
I am on beta 18 now. It's not working so far. 

![Screenshot_20230821_235105_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/9374ab64-a77f-4dc4-a966-668a218978a6)
[config_entry-smart_irrigation-6fed4dd1802cfe6d10301f4d0f40418e-1.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12402893/config_entry-smart_irrigation-6fed4dd1802cfe6d10301f4d0f40418e-1.txt)

**Comment by jeroenterheerdt** [comment]
I have no idea what is going on here. I works fine on my side (but I am using a '.' as decimal separator since that is my config on my PC). I notice you are doing this on mobile, have you tried doing this on a PC? Just wondering what could be causing this.

**Comment by jeroenterheerdt** [comment]
I noticed there is a small difference between how size and throughput are handled and how multiplier is handled. The reason is that size and throughput need to be a positive decimal number (negative size/throughput does not make sense) but multiplier can be negative. Multiplier is handled the same as bucket, for example. Can you try the following things:
1) Set bucket to a decimal number. Is that number persisted when you change pages or do the decimals disappear just like Multiplier? If so, then there is a bug in how those are handled in an underlying component so I need to find a way to work around it.
2) Change [line 159 in `websockets.py` ](https://github.com/jeroenterheerdt/HAsmartirrigation/blob/v2.0/custom_components/smart_irrigation/websockets.py#L159)on your machine from `vol.Optional(const.ZONE_MULTIPLIER): vol.Coerce(float),` to `vol.Optional(const.ZONE_MULTIPLIER): cv.positive_float,`. Save the file, restart HA and try setting a decimal number for multiplier.

Let me know what you find

**Comment by DanDan800** [comment]
Hi, I don't know what was going on, but now multiplier works with decimals (without any changes) on beta 18. 
The bucket can handle decimals as well. 
What i realized today is, that the version title yesterday was "Smart Irrigation
v2023.8.0-beta16",  even after removing beta16 and new installation of beta 18.
The config file also showed beta 18. Maybe my fault. 

![Screenshot_20230822_101306_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/892eb70f-ad68-42e3-bd20-b893592920dc)

**Comment by jeroenterheerdt** [comment]
Not your fault, I think a cache problem on your device. Glad we found it!
