### ISSUE TITLE
Module 1:static is duplicated after entering delta value 

### ISSUE THREAD

**Issue by DanDan800** [jeroenterheerdt/HAsmartirrigation#164]
### What happened?

When changing the delta value of existing module "1:static", an additional module appears as an duplicate. 
The value of the duplicate can not be changed. 
Deleting the duplicated module is possible. 
Adding of further modules is possible. 
Deleting the module 1:static and 2:passthrough is not possible. 
![Screenshot_20230820_120540_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/c70c9059-aef5-493d-92e0-9d194232c48b)
![Screenshot_20230820_120558_Home Assistant](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/87934334/4401d197-4947-4b96-abf2-b8631b84e686)

### How to reproduce

Can be reproduced by changing value. 

### Relevant log output

```shell
No log output
```

### Which version are you running?

Beta 14

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-d309574885fe55cb4f63702993289a78-6.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12387927/config_entry-smart_irrigation-d309574885fe55cb4f63702993289a78-6.txt)

**Comment by jeroenterheerdt** [comment]
this is caused by some or your modules still having string type IDs, not numeric. I switched to numeric IDs (int) for zones/modules/mappings. There are two ways of getting out of this state:
1) easiest: uninstall the component, reboot HA, install the component.
2) harder: go into hidden storage folder and edit storage file for smart irrigation. Make sure all IDs for zones/modules/mappings are ints, so something like: `id: 0,` and not `id: "0",`

Just upgrading to the next beta is not going to help you here.

**Comment by DanDan800** [comment]
The easy way helped me out. Now it works with beta 16 after new installation
