### ISSUE TITLE
smart_irrigation.calculate_zone Error executing script

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#173]
### What happened?

I started a calculation on a single zone. The GUI exposed an "Unknown Error"

### How to reproduce

Run smart_irrigation.calculate_zone on a single zone.

### Relevant log output
```
shell
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/smart_irrigation/__init__.py:592
Integration: Smart Irrigation (documentation, issues)
First occurred: 20:33:42 (1 occurrences)
Last logged: 20:33:42

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: pop expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 793, in handle_calculate_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 592, in async_update_zone_config
    data.pop(const.ATTR_CALCULATE, None)
TypeError: pop expected at most 1 argument, got 2
```

and 
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smart_irrigation/__init__.py:592
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:33:42 (1 occurrences)
Last logged: 20:33:42

[140021454348096] Error handling message: Unknown error (unknown_error) Christoph from 192.168.178.100 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 716, in handle_execute_script
    response = await script_obj.async_run(msg.get("variables"), context=context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 793, in handle_calculate_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 592, in async_update_zone_config
    data.pop(const.ATTR_CALCULATE, None)
TypeError: pop expected at most 1 argument, got 2
```
and 
```
This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:640
Integration: Smart Irrigation (documentation, issues)
First occurred: 20:42:56 (2 occurrences)
Last logged: 20:43:15

Calculate zone Bewässerung Küche failed: no data available.
```

### Which version are you running?

v2023.8.0-beta17

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12399680/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)
```

**Comment by jeroenterheerdt** [comment]
should be fixed in beta 18. please confirm and close.

**Comment by gatonero** [comment]
On  v2023.8.0-beta18

Strange behaviour!.

- First run without any error, but doesn't change any value.
- Second run with errors, also doesn't change any value.

```
This error originated from a custom integration.


Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:792
Integration: Smart Irrigation (documentation, issues)
First occurred: 21:43:50 (3 occurrences)
Last logged: 21:43:50

Calculate for zone Bewässerung Wohnzimmer failed: no data available.
Calculate for zone Bewässerung Terrasse failed: no data available.
Calculate for zone Bewässerung Küche failed: no data available.
```

**Comment by jeroenterheerdt** [comment]
well, the second is expected: there is no data after a calc has happened.
remember: updating is collecting weatherdata, calculating is taking the collected weatherdata and deciding how long to irrigate for. So the fact that you see the warnings in the log the second time around makes sense, as all weatherdata was removed after the calc has happened and I assume you haven't done an update in between the first and second calculate.
Now, the first is not a bug for sure, but might be. Did you update before you calculated the first time? If so, then this is likely not a bug and the explanation in the panel should tell what calculations were done.
To really get to the bottom of this, do the following:
1) Call Calculate All, just to remove all colllected weatherdata so we start with a clean slate
2) Call Update on the zone you want collect weatherdata for or update all of course.
3) Generate and store a diagnostic file. If you look at it, it should include data for your mappings (which means the weatherdata was retrieved and stored).
4) Call Calculate on the zone you want to calculate or calculate all zones. Any automatic zones that have mappings that have weatherdata should update.
5) Generate another diagnostic file and compare to the previous. the mapping data should be gone and the zones that were updated should potentially have some values updated (bucket/duration) and an explanation set.

I can also help with investiging if you upload the mentioned diagnostics files. Again, I am not sure this is a bug. It works on my side as expected (i.e. calculate takes weatherdata if it is there and otherwise returns a warning).

**Comment by gatonero** [comment]
Here are both diagnostic files. 01 from Step 3 and 02 from step 5

[config_entry-smart_irrigation-01.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12402094/config_entry-smart_irrigation-01.json.txt)

[config_entry-smart_irrigation-02.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12402095/config_entry-smart_irrigation-02.json.txt)

**Comment by jeroenterheerdt** [comment]
ok, so the 01 file (from after you updated, but before you calculated):
zone (id = 0): bucket = -2.0. The mapping (id = 1) has the following data:
`
"data": [
            {
              "Dewpoint": 15.4,
              "Humidity": 77.0,
              "Maximum Temperature": 26.7,
              "Minimum Temperature": 17.2,
              "Precipitation": 0.0,
              "Pressure": 1022.1,
              "Solar Radiation": 0.0,
              "Temperature": 19.5,
              "Windspeed": 0.0
            }
`

Then in the 02 file (after you calculated), the zone (id=0) was not updated because no ET value was returned (0). I found a bug that caused this which was only apparent once I moved my system to metric instead of US units. Anyway, afterwards the zone got updated. I will ship beta 19 soon.

**Comment by gatonero** [comment]
Now on v2023.8.0-beta19

For me it looks good now.

To be sure I attach both config files, generated te same way as before.

[config_entry-smart_irrigation-01.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12407697/config_entry-smart_irrigation-01.json.txt)

[config_entry-smart_irrigation-02.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12407699/config_entry-smart_irrigation-02.json.txt)
