### ISSUE TITLE
Calculate all fails with 'forecast' error

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#182]
### What happened?

This error originated from a custom integration.

Logger: aiohttp.server Source: custom_components/smart_irrigation/init.py:382 Integration: Smart Irrigation (documentation, issues) First occurred: 9:17:31 PM (1 occurrences) Last logged: 9:17:31 PM

Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/websockets.py", line 174, in post await coordinator.async_update_zone_config(zone, data) File "/config/custom_components/smart_irrigation/init.py", line 680, in async_update_zone_config await self._async_calculate_all() File "/config/custom_components/smart_irrigation/init.py", line 382, in _async_calculate_all if modinst and modinst.name=="PyETO" and modinst.forecast>0: ^^^^^^^^^^^^^^^^ AttributeError: 'PyETO' object has no attribute 'forecast'

### How to reproduce

calculate all

### Which version are you running?

beta

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
@dlindnegm can you please confirm that this is fixed in beta 22 and close the bug?

**Comment by dlindnegm** [comment]
Confirmed - beta 22 resolves the issue with error:
 AttributeError: 'PyETO' object has no attribute 'forecast'

I think you need to close this one #182
Thanks!

**Comment by dlindnegm** [comment]
A question on the run time values I'm seeing:

6 sq ft   1.4705 gpm
PyETO w/ no forecast   Using my sensors
Multiplier 1 = 906 seconds run time (15 min) (22 gal)
Multiplier 0.08 = 71 seconds

I know from experience that the daily water for that zone shouldn't need to be over 60 seconds, so I've needed to reduce the multiplier from 1.0 to 0.08 in order to bring the run time into a reasonable range.  Is it normal to need to use such a small multiplier value?  22 gallons would be enough to water that area for a full month, way more than needed to replace a single days evapotranspiration!   I would have thought that the results would at least be in the ball park and not need such a large adjustment.  This zone consists of several hanging potted plants so I know to reduce the multiplier, but how would I know how much to reduce it for a larger zone such as a several thousand square foot grass yard?

**Comment by jeroenterheerdt** [comment]
closing this, can you please open an issue for your last comment so we keep things separated?
