### ISSUE TITLE
[REQ] perform an update just before calculate if no weather data is available

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeroenterheerdt** [comment]
@dlindnegm do you still believe this is a good idea? (see title)

**Comment by dlindnegm** [comment]
I think that since you have options for scheduling both an automatic update and calculate it makes sense to **_not perform the update just prior to a calculate_**.  Folks that are basing their watering automation on the duration sensor rising above zero can assume that the update must have occurred, otherwise that value would still be zero.  And they will need to have enough knowledge of the entire process to be able to either schedule the update in the GUI or initiate it via a service call, as well as needing to reset the buckets. You might want to consider flipping those options on the General tab, since the update needs to occur before the calculate.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/c25ef295-986e-4bbe-b70b-ce9fa698cef0)

**Comment by jeroenterheerdt** [comment]
thanks, but today these are in the right order then... auto update is at the top, auto calc is second. that is the order it should be done in.

**Comment by dlindnegm** [comment]
Calculate is on top in my GUI - I screen captured it and reversed it in that image!

**Comment by jeroenterheerdt** [comment]
> Calculate is on top in my GUI - I screen captured it and reversed it in that image!

WHAT? Then that does not make sense. I will create a separate bug for that :) thanks for catching that

**Comment by jeroenterheerdt** [comment]
Deciding not to do this.
