### ISSUE TITLE
REQ: few tiny improvements

### ISSUE THREAD

**Issue by ciechompl** [jeroenterheerdt/HAsmartirrigation#24]
just for transparency ... please add to base sensor attributes the following info from setup: 
-  Local time to schedule automatic refresh (if enabled).
- automatic refresh: enabled/disabled
- Number of seconds to run irrigation when in force mode.
and any other you introduce in the future. 
it's nothing but maybe someone will want to display all options set for this integration somewhere in the fronted. 

Second tiny thing is that units_of_measurement for every option showed in attributes could be added to the name of the attribute e,g, ( throughput [ l/min ]: 150.0 ) when "Show units in entity attributes" disabled in config. When enabled it is obvious where we will gonna see them :)

**Comment by jeroenterheerdt** [comment]
I am going to fix part of this in the next release (v0.0.21). I am not going to rename attributes on the fly. I will leave them like this for now, since it is also dependent on imperial / metric system. I trust everyone can just understand it by thinking about it a bit. Other items have been added in v0.0.21
