### ISSUE TITLE
No translateable fields for PyETO Modul and updtae weather data

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#285]
### What happened?

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/9bb659d1-3d8f-4df1-beaa-f08ebfa0cfdf)

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/114430e4-cefd-45a9-9e83-067a7ea6a9db)

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/8663b141-d4d0-42d2-b44c-116acae23f1b)

### How to reproduce

Open "Module"

### Which version are you running?

v2023.9.1

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Modules parameters don't translate. That is by design. The other one is a bug.

**Comment by jeroenterheerdt** [comment]
@gatonero so the reason the label you indicated in the config is English is because that's our fallback language in case the language doesn't have a translation for it. In your case the German file doesn't have this translation yet but the English one does. Now, maybe you already translated it and I missed it during merging (my mistake). Please compare the files, specifically this line: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/custom_components/smart_irrigation/frontend/localize/languages/en.json#L32

**Comment by jeroenterheerdt** [comment]
this should hopefully be solved with merging the changes you made against v2 branch. Please verify and close.

**Comment by gatonero** [comment]
"Automatic update weather data" is now translated.

The modules aren't translated, as designed.
