### ISSUE TITLE
Unable to set OWM API key

### ISSUE THREAD

**Issue by f1ren** [jeroenterheerdt/HAsmartirrigation#314]
### What happened?

[config_entry-smart_irrigation-35167bd098173185c9993fb1912aecef.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/13243688/config_entry-smart_irrigation-35167bd098173185c9993fb1912aecef.json.txt)

### Steps
* Smart Irrigation upgraded to V2
* Zones configured
* Default sensor group selected

### Result
* No place to insert my OWM API
* OpenWeatherMap source is disabled
<img width="306" alt="image" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/2501137/8411365c-e92b-4849-8d7a-1465d0069a39">

* All buckets remain empty after updating/calculating 😔

### How to reproduce

* Upgrade from V1 to V2
* Repeat the steps above

### Which version are you running?

v2023.9.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
you should have seen it when installing. Since you have already installed it, go into 'configuration':
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8188990/2e29e6f4-7e79-4189-89ea-f293a7420819)

The second screen asks you to enter the OWM api key, assuming you did not deselect it in the first screen.
