### ISSUE TITLE
[REQ] Sonoff LAN support

### ISSUE THREAD

**Issue by lorenzing** [jeroenterheerdt/HAsmartirrigation#34]
Hi, 
I'm new to home assistant world, I installed your component, I was wondering if I can use it to control my two irrigation valves, managed by two SV sonoff with this integration: https://github.com/AlexxIT/SonoffLAN (for original firmware). At the moment I have the two working switches (switch.sonoff_10007ca422 & switch.sonoff_10007ca743) how can I insert them in irrigation.yaml?
I'm sorry if the questions are trivial, thank you very much for your help.

**Comment by jeroenterheerdt** [comment]
hi and welcome to the world of Home Assistant! You should absolutely be able to control the valves with this component, but as you can see in the [Readme ](https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/README.md)this component does not interact with your valves directly - it provides you with the information required though. See this for example on how to set this up: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/README.md#step-3-creating-automation. Now since you have two valves I assume the number of sprinklers and throughput for the valves / zones is different. If so, I would add this component twice (once for each zone) and build two automations (one for each zone). If the zones are identical, you can add the component once and just build one automation that controls both valves.
