### ISSUE TITLE
Changing the bucket - no impact on duration

### ISSUE THREAD

**Issue by elenril2** [jeroenterheerdt/HAsmartirrigation#347]
### What happened?

When calling service _set_bucket_, I think there should be a change in the state of a given zone, directly affecting the irrigation time.

### How to reproduce

Call service _set_bucket_

### Relevant log output

There was no bucket change recorded in the [log](https://github.com/jeroenterheerdt/HAsmartirrigation/files/14977407/config_entry-smart_irrigation-f2f59f4233cca0fb6e63c993212765fb.1.json).

### Which version are you running?

v2024.4.3

### Diagnostics file

- [x] I have attached a diagnostics file

### Additional information

I'm not sure if this is a bug, but I think there was this functionality in v1. When calling service _set_bucket_, there should be a change in the state of a given zone (seconds of watering), directly affecting the irrigation time.

I don't want to run the service _update_zone_ because it will just recalculate the bucket and erase the existing weather data points.

**Comment by jeroenterheerdt** [comment]
Investigating.

**Comment by jeroenterheerdt** [comment]
so we split the update and calculate steps in v2, which were one and the same in v1.
that is causing this behavior.
the issue here is that if we implemented what you suggested and effectively calculated after a bucket is set, we would also be removing the weatherdata used to calculate (that is an effect of calculate) and I am quite certain that is something we don't want as once the weatherdata is gone it's gone for all the zones that use that weatherdata. So you set one bucket (and calculated), but all other zones can now not calculate anymore based on the weatherdata collected so far. never say never, but its pretty hard to make this happen in this new set up. 

How hard is it for you to change your logic to the following:
-call set_bucket for the zones
-call calculate

**Comment by elenril2** [comment]
OK, thanks for your answer. I will use such a logic.
I thought it was possible to just change the irrigation time (zone state) based on the bucket, without touching the weather data.

**Comment by jeroenterheerdt** [comment]
You are not wrong. I will keep thinking about this but I don't see a quick solution here yet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
