### ISSUE TITLE
register_static_path is deprecated because it does blocking I/O in the event loop

### ISSUE THREAD

**Issue by clau-bucur** [jeroenterheerdt/HAsmartirrigation#429]
### What happened?

Upon start, HA logs the following warning:
```
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False), please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues
```

### How to reproduce

Just restart HA.

Diagnostics file: [config_entry-smart_irrigation-54a29ef14b286103055503f5030ddb5a.json](https://github.com/user-attachments/files/16163780/config_entry-smart_irrigation-54a29ef14b286103055503f5030ddb5a.json)

### Which version are you running?

2024.7.4

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
thanks - I noticed this too but it seems like it's a bit too early to move to this other function as I ran into compat issues.

**Comment by lucode** [comment]
Ok this issue seems not to cause problems with HA Automations, but it certainly does if you are using Node Red.
Since about 3 month I have severe troubles with Node Red, in various ways. And it seems that I'm not the only one, but I can't verify if others have installed Smart Irrigation too.

The issues caused 3 types of problems.

1. Very slow communication between HA and Node Red, see issue https://github.com/hassio-addons/addon-node-red/issues/1923
2. Constant errors in Node Red, "Entity could not be found in cache for entityId:"
3. Various severe issues if you are using Node Red Companion Integration see: https://github.com/zachowj/hass-node-red/issues/300

I would be very happy if someone could fix this issue, unfortunately I can't help.
