### ISSUE TITLE
Gardena Sensors not taken into consideration

### ISSUE THREAD

**Issue by w1Ngx** [jeroenterheerdt/HAsmartirrigation#456]
### What happened?

Gardena Humidity Sensor shows 15%, still 0 duration for the zone calculated

### How to reproduce

click calculate

### Relevant log output

```shell
none - more a question on how i can check if the sensor is ignored?
```

### Which version are you running?

2024.7.8

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-3449ac96973de5ce532ac215b3e02eb6.json](https://github.com/user-attachments/files/16408649/config_entry-smart_irrigation-3449ac96973de5ce532ac215b3e02eb6.json)

**Comment by w1Ngx** [comment]
Yes 2 sensors are maintained. Would there be an error message if it can’t read them?
![IMG_2500](https://github.com/user-attachments/assets/70102026-acee-4f92-af46-7a3a8fc81dc1)

**Comment by jeroenterheerdt** [comment]
It should log an error, but turn on debug logging to find if anyone is going wrong. Did you look at the logs at all?

**Comment by w1Ngx** [comment]
[home-assistant_smart_irrigation_2024-07-31T18-08-24.008Z.log](https://github.com/user-attachments/files/16445607/home-assistant_smart_irrigation_2024-07-31T18-08-24.008Z.log)

**Comment by Dr-ead** [comment]
As far as I understand, you need to use an air humidity not a soil moisture sensor! As in your screenshot, it is a soil moisture/humidity sensor. Smart irrigation has no input for soil moisture sensors.
So you can argue if the calculation is correct, when your soil moisture is 15% and there is no irrigation, if everything else is setup correctly and works properly.

But I observe a similar issue here using smart irrigation to irrigate my flower garden. I think the calculation is more or less correct. But if you look on my soil moisture sensors, it doesn't fit. So I think I must play arround with the parameters of maximum bucket size and also apply a real soil moisture start level, from which smart irrigation calculates on. Especially if you let the system not irrigate for e.g. 5 days and there was one short but heavy rain shower on one day otherwise it was hot and sunny, the calculation doesn't fit anymore, as the soil moisture is reducing extremly over these days but the calculated bucket size is still positive. So in my opinion the soil is not saving the water as assumed.

**Comment by w1Ngx** [comment]
The humidity and temperature are for air, not soil? isn’t soil measuring the most accurate indicator for water needs? 

If it’s like that i assume weather service is a better choice and the soil measuring will be irrelevant, or is there any good use of it in this integration?

**Comment by jeroenterheerdt** [comment]
yes, humidity and temperature are for air, not soil.
Soil sensors are not a good way to measure watering needs: they spike and drop off real quick (just put some water on your soil sensor and observe the data). Also, they are point solutions (so unless you want to invest in putting soil sensors every 2 meters they are useless). The industry standard on which this integration is based does not use soil sensors at all, for these reasons.

So to call this integration useless or irrelevant is a bit of a stretch. In fact, it's the opposite: soil humidity sensors are useless.

Anyway as a way to make sure you don't have to invest in anything: no sensors, not weather station... you can use this integration with just a weather service. However, the better way of doing this is get a weather station and use that data.
