### ISSUE TITLE
[REQ] Sprinklers and micro-drip systems

### ISSUE THREAD

**Issue by rugaard** [jeroenterheerdt/HAsmartirrigation#61]
Sorry for creating a ticket, but since the discussion board isn't enabled for the project, this is the only way to reach you.

I've fully managed to install and setup the integration. Calculations working, automations are working, everything works like a charm. Huge thanks and thumbs up for that.

But I have a question in regards to the configuration of the integration. I'm a bit confused to what value I should put into the `sprinklers` option, but I don't really have a sprinkler but rather a "dripping system". 

I'm running a 25 meter long [Gardena micro-drip system](https://www.gardena.com/int/products/watering/micro-drip/) in my garden and I just assumed that would only count as `1 spinkler`. But suddenly I'm starting to be unsure if this is actually the case? Would every "hole" in the drip line actually count as a sprinkler for the integration to work properly?

The reason for my sudden insecurity is that I've seen that it's possible to add "fine rain spinklers" to each of these existing holes in the drip line, which then would mean I could potentially add **a lot** of sprinklers.

I hope my question make sense and hope that you can help me out. Or at least tell what you would recommend me putting in as a value in the `sprinklers` option.

Thanks again for an incredible integration. I really, really love it!

**Comment by jeroenterheerdt** [comment]
Hi, thanks for reaching out and of course opening a ticket is perfectly fine! Glad you like the integration. To answer your question: the sprinkler count is just used to calculate the total water throughput of the system. So if you know the total output of your hoses you can just enter 1 sprinkler and enter the total throughput capacity as the throughput per sprinkler. Hope this helps!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Morten Rugaard ***@***.***>
Sent: Friday, June 4, 2021 12:18:12 PM
To: jeroenterheerdt/HAsmartirrigation ***@***.***>
Cc: Jeroen ter Heerdt ***@***.***>; Assign ***@***.***>
Subject: [jeroenterheerdt/HAsmartirrigation] [REQ] Sprinklers and micro-drip systems (#61)


Sorry for creating a ticket, but since the discussion board isn't enabled for the project, this is the only way to reach you.

I've fully managed to install and setup the integration. Calculations working, automations are working, everything works like a charm. Huge thanks and thumbs up for that.

But I have a question in regards to the configuration of the integration. I'm a bit confused to what value I should put into the sprinklers option, but I don't really have a sprinkler but rather a "dripping system".

I'm running a 25 meter long Gardena micro-drip system<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gardena.com%2Fint%2Fproducts%2Fwatering%2Fmicro-drip%2F&data=04%7C01%7C%7C1edeed87a455460f344508d9278d7fbb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637584310948363286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QWN4qdSsxI18HxWyqh7UvW%2F0K40LrgkgUKsZunlKGf8%3D&reserved=0> in my garden and I just assumed that would only count as 1 spinkler. But suddenly I'm starting to be unsure if this is actually the case? Would every "hole" in the drip line actually count as a sprinkler for the integration to work properly?

The reason for my sudden insecurity is that I've seen that it's possible to add "fine rain spinklers" to each of these existing holes in the drip line, which then would mean I could potentially add a lot of sprinklers.

I hope my question make sense and hope that you can help me out. Or at least tell what you would recommend me putting in as a value in the sprinklers option.

Thanks again for an incredible integration. I really, really love it!

**Comment by rugaard** [comment]
@jeroenterheerdt Thank you for your quick reply.

That make sense. On the box of my drip-line it says 4 L/h in regards to water flow. Now the question is just if it for the entire drip-line or per hole in the drip-line. Looks like I have some investigation to do.

Thanks again for your big effort with this integration 🙏

**Comment by Arquiteto** [comment]
@rugaard The easiest way to check I think is to write down your water meter state, open valve for 2-3 minutes and calculate what would be your real hourly output.

**Comment by daxy01** [comment]
> @jeroenterheerdt Thank you for your quick reply.
> 
> That make sense. On the box of my drip-line it says 4 L/h in regards to water flow. Now the question is just if it for the entire drip-line or per hole in the drip-line. Looks like I have some investigation to do.
> 
> Thanks again for your big effort with this integration 🙏

I believe (according to https://www.wildkamp.nl/assortiment/beregening/druppelbevloeiing/druppelslangen/5001020) the water flow reported is liters per 33cm. In my case I've added these values:

- number of sprinklers: 1
- flow 5 l/m (50m / 0.33  * 2 l/h = 303 l/h / 60min = 5.05 l/m)
- throughput = 5
- Area = 50 (50 m drip-line)

This resulted in a daily run-time of approx 30-40min during the past week which in our Dutch climate last week seems to be sufficient and what I'd expect. 

Hope this helps!

**Comment by jeroenterheerdt** [comment]
closing this issue because of staleness, please re-open an issue if this is still a problem in 2.0 version (now in beta)
