### ISSUE TITLE
Rain forecast

### ISSUE THREAD

**Issue by freekeys** [jeroenterheerdt/HAsmartirrigation#62]
Hello, is there anything built into the algorithm to account for forecast rain? Thanks!

**Comment by jeroenterheerdt** [comment]
no. it just looks at what happened the day before and responds accordingly.

**Comment by freekeys** [comment]
Thanks, I just read your wiki though and see that checking if hourly adjusted run time > 0 does help with this. Just to help me understand, why do you not just generally use the hourly adjusted time instead of daily?

**Comment by jeroenterheerdt** [comment]
Hourly adjusted run time can tell you if more moisture has evaporated from the soil than was added in the last hour. Since this component is built to work on a daily scale, we take the hourly ART and average it to get the daily ART. There is no forecasting anywhere.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by freekeys** [comment]
Got it, thanks!

**Comment by freekeys** [comment]
Quick question - is it possible to configure through YAML? And if not, is it possible to go back and change my set up settings through my config flow? Think I must have got a flow rate wrong

**Comment by jeroenterheerdt** [comment]
YAML config is not supported. You can change the settings by editing the file in the `.storage` folder under config. but you are on your own there.

**Comment by freekeys** [comment]
Thanks
